name: deploy ec2
on: push
jobs:
runs-on: ubuntu-latest
steps:
  - name: check out the code
    uses: actions/checkout@v3
  - name: confirgure aws
    uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    -  name: set up terraform
       uses: hashicorp/setup-terraform@v3
       with: 
       terraform_version: 1.6.6
    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve
      
